<?php

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class SchemagicOptions
{
	private $schemagic_options_options;

	public function __construct()
	{
		add_action('admin_menu', array($this, 'schemagic_options_add_plugin_page'));
		add_action('admin_init', array($this, 'schemagic_options_page_init'));
	}

	public function schemagic_options_add_plugin_page()
	{

		add_submenu_page(
			'edit.php?post_type=schemagic', // Parent menu slug (the custom post type menu)
			'Schemagic Options', // Page title
			'Schemagic Options', // Menu title
			'manage_options', // Capability required to access this menu
			'schema-org-options', // Menu slug
			array($this, 'schemagic_options_create_admin_page') // function
		);
	}

	public function schemagic_options_create_admin_page()
	{
		$this->schemagic_options_options = get_option('schemagic_opt'); ?>

		<div class="wrap">
			<h2>Schemagic Options</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
				settings_fields('schemagic_options_option_group');
				do_settings_sections('schemagic-options-admin');
				submit_button();
				?>
			</form>
		</div>
	<?php }

	public function schemagic_options_page_init()
	{
		register_setting(
			'schemagic_options_option_group', // option_group
			'schemagic_opt', // option_name
			array($this, 'schemagic_options_sanitize') // sanitize_callback
		);

		add_settings_section(
			'schemagic_options_setting_section', // id
			'Settings', // title
			array($this, 'schemagic_options_section_info'), // callback
			'schemagic-options-admin' // page
		);

		add_settings_field(
			'enable', // id
			'Enable Plugin', // title
			array($this, 'enable_callback'), // callback
			'schemagic-options-admin', // page
			'schemagic_options_setting_section' // section
		);

		add_settings_field(
			'location', // id
			'Location', // title
			array($this, 'location_callback'), // callback
			'schemagic-options-admin', // page
			'schemagic_options_setting_section' // section
		);
	}

	public function schemagic_options_sanitize($input)
	{
		$sanitary_values = array();
		if (isset($input['enable'])) {
			$sanitary_values['enable'] = $input['enable'];
		}

		if (isset($input['location'])) {
			$sanitary_values['location'] = $input['location'];
		}

		return $sanitary_values;
	}

	public function schemagic_options_section_info()
	{
	}

	public function enable_callback()
	{
		printf(
			'<input type="checkbox" name="schemagic_opt[enable]" id="enable" value="enable" %s>',
			(isset($this->schemagic_options_options['enable']) && $this->schemagic_options_options['enable'] === 'enable') ? 'checked' : ''
		);
	}

	public function location_callback()
	{
	?> <select name="schemagic_opt[location]" id="location">
			<?php $selected = (isset($this->schemagic_options_options['location']) && $this->schemagic_options_options['location'] === 'manual') ? 'selected' : ''; ?>
			<option value="manual" <?php echo $selected; ?>>Manual</option>
			<?php $selected = (isset($this->schemagic_options_options['location']) && $this->schemagic_options_options['location'] === 'header') ? 'selected' : ''; ?>
			<option value="header" <?php echo $selected; ?>>Header</option>
			<?php $selected = (isset($this->schemagic_options_options['location']) && $this->schemagic_options_options['location'] === 'footer') ? 'selected' : ''; ?>
			<option value="footer" <?php echo $selected; ?>>Footer</option>
		</select> <?php
				}
			}
			if (is_admin())
				$schemagic_options = new SchemagicOptions();
